---
name: Audit - Dependency Scanning - NPM

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      solution:
        description: The path to the solution file to test (e.g., src/MyProject.sln)
        required: true
        type: string
      dotnetVersion:
        description: 'The version of the .NET SDK to use for the tests (default: 8.0.x)'
        required: false
        default: 8.0.x
        type: string
      nugetSourceUrl:
        description: 'The URL of the NuGet source to use for restoring packages (default: https://api.nuget.org/v3/index.json)'
        required: false
        default: https://api.nuget.org/v3/index.json
        type: string
      enableCache:
        description: 'Whether to enable caching for the .NET SDK (default: false). Enabling caching can speed up the workflow by reusing previously downloaded packages and dependencies, but requires
                      a package lock file to be present in the repository.'
        required: false
        default: false
        type: boolean
    secrets:
      nugetAuthToken:
        description: 'The Personal Access Token (PAT) for accessing the private NuGet feed.'
        required: false

env:
  solutionPath: ${{ inputs.solution }}

jobs:
  test:
    name: Tests - .NET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Setup dotnet ${{ inputs.dotnetVersion }}
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2
        with:
          dotnet-version: ${{ inputs.dotnetVersion }}
          source-url: ${{ inputs.nugetSourceUrl }}
          cache: ${{ inputs.enableCache }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.nugetAuthToken }}

      # Note: Your global.json must specify your input version of dotnet, otherwise the setup-dotnet action will not use the correct dotnet version.
      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionPath }}

      - name: Run package audit
        run:  |
              dotnet list ${{ env.solutionPath }} package --no-restore --vulnerable --include-transitive 2>&1 | tee build.log
              echo 'Analyse dotnet list package command log output...'
              if grep -q -i 'critical\|high' build.log; 
              then
                  echo 'Must fix security vulnerabilities found on the log output.'
                  exit 1
              else
                  echo 'No critical or high severity vulnerabilities found.'
                  exit 0
              fi