---
name: Audit - Trivy Container Scanning

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      context:
        description: 'The context to use for the Docker build (default: current directory)'
        required: false
        default: .
        type: string
      dockerfilePath:
        description: 'The path to the Dockerfile to use for the build (default: Dockerfile)'
        required: false
        default: Dockerfile
        type: string
    secrets:
      buildArgs:
        description: Build arguments to pass to the Docker build command (optional).
                     You must pass the flag in the format --build-arg ARG_NAME=ARG_VALUE.
                     Multiple build arguments can be passed by separating them with spaces.
        required: false

jobs:
  build:
    name: Audit - Trivy Container Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Build an image from Dockerfile
        run: docker build -t funding-service-trivy-scan:${{ github.sha }} -f ${{ inputs.dockerfilePath }}
             ${{ secrets.buildArgs }} ${{ inputs.context }} 

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: funding-service-trivy-scan:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL
